version: '3.8'

services:
  django:
    build: .
    container_name: receipt_api
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&  python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/my_project
    ports:
      - 8000:8000
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
