openapi: 3.0.3
info:
  title: Simple CRUD Receipt API
  version: 1.0.0
  description: Test assignment
paths:
  /receipts/:
    get:
      operationId: receipts_list
      parameters:
      - in: query
        name: created_on
        schema:
          type: string
          format: date-time
      - in: query
        name: date_after
        schema:
          type: string
          format: date-time
        description: date
      - in: query
        name: date_before
        schema:
          type: string
          format: date-time
        description: date
      - in: query
        name: id
        schema:
          type: integer
      - in: query
        name: item
        schema:
          type: string
      - in: query
        name: items
        schema:
          type: array
          items:
            type: integer
        explode: true
        style: form
      tags:
      - receipts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Receipt'
          description: ''
    post:
      operationId: receipts_create
      tags:
      - receipts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Receipt'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Receipt'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Receipt'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
          description: ''
  /receipts/{id}/:
    get:
      operationId: receipts_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this receipt.
        required: true
      tags:
      - receipts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
          description: ''
    put:
      operationId: receipts_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this receipt.
        required: true
      tags:
      - receipts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Receipt'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Receipt'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Receipt'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
          description: ''
    patch:
      operationId: receipts_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this receipt.
        required: true
      tags:
      - receipts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedReceipt'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedReceipt'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedReceipt'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
          description: ''
    delete:
      operationId: receipts_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this receipt.
        required: true
      tags:
      - receipts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Item:
      type: object
      properties:
        product_name:
          type: string
          maxLength: 50
      required:
      - product_name
    PatchedReceipt:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_on:
          type: string
          format: date-time
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Receipt:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_on:
          type: string
          format: date-time
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
      required:
      - created_on
      - id
      - items
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
